name: Test Changes
on: [push, pull_request]
jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
